/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserPreference } from '../../models/user-preference';

export interface GetUserPreferences$Params {
  userId: number;
}

export function getUserPreferences(http: HttpClient, rootUrl: string, params: GetUserPreferences$Params, context?: HttpContext): Observable<StrictHttpResponse<UserPreference>> {
  const rb = new RequestBuilder(rootUrl, getUserPreferences.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserPreference>;
    })
  );
}

getUserPreferences.PATH = '/api/notifications/preferences/{userId}';
