services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: projecthub-frontend:latest
    container_name: projecthub-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "project=projecthub"
      - "service=frontend"
      - "environment=local"

networks:
  frontend-network:
    driver: bridge
    name: projecthub-frontend-network

volumes:
  frontend-logs:
    driver: local
    name: projecthub-frontend-logs
