/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddMemberRequest {
  role?: 'OWNER' | 'ADMIN' | 'MEMBER' | 'VIEWER';
  userId: string;
}
