/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskDto } from '../models/task-dto';
export interface ApiResponseTaskDto {
  data?: TaskDto;
  message?: string;
  success?: boolean;
  timestamp?: string;
}
