/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageTaskDto } from '../models/page-task-dto';
export interface ApiResponsePageTaskDto {
  data?: PageTaskDto;
  message?: string;
  success?: boolean;
  timestamp?: string;
}
