/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { KanbanBoardDto } from '../models/kanban-board-dto';
export interface ApiResponseKanbanBoardDto {
  data?: KanbanBoardDto;
  message?: string;
  success?: boolean;
  timestamp?: string;
}
