/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectStatsDto } from '../models/project-stats-dto';
export interface ApiResponseProjectStatsDto {
  data?: ProjectStatsDto;
  message?: string;
  success?: boolean;
  timestamp?: string;
}
