/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectDto } from '../models/project-dto';
export interface ApiResponseProjectDto {
  data?: ProjectDto;
  message?: string;
  success?: boolean;
  timestamp?: string;
}
