/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DashboardDto } from '../models/dashboard-dto';
export interface ApiResponseDashboardDto {
  data?: DashboardDto;
  message?: string;
  success?: boolean;
  timestamp?: string;
}
