/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DashboardStats {
  activeSprints?: number;
  completedTasksThisWeek?: number;
  myOpenTasks?: number;
  overdueTasksCount?: number;
  totalProjects?: number;
  totalTasks?: number;
}
