/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskDto } from '../models/task-dto';
export interface KanbanColumn {
  id?: string;
  name?: string;
  status?: string;
  taskCount?: number;
  tasks?: Array<TaskDto>;
  wipLimit?: number;
}
