/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SimpleProjectDto {
  createdAt?: string;
  description?: string;
  id?: string;
  key?: string;
  name?: string;
  priority?: string;
  status?: string;
}
