/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SimpleTaskDto {
  assigneeId?: string;
  createdAt?: string;
  description?: string;
  id?: string;
  priority?: string;
  reporterId?: string;
  status?: string;
  storyPoints?: number;
  taskKey?: string;
  taskType?: string;
  title?: string;
}
