/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskDto } from '../models/task-dto';
export interface SprintDto {
  completedStoryPoints?: number;
  completedTasks?: number;
  createdAt?: string;
  createdBy?: string;
  createdByName?: string;
  endDate?: string;
  goal?: string;
  id?: string;
  name?: string;
  projectId?: string;
  projectName?: string;
  startDate?: string;
  status?: 'PLANNING' | 'ACTIVE' | 'COMPLETED' | 'CANCELLED';
  taskCount?: number;
  tasks?: Array<TaskDto>;
  totalStoryPoints?: number;
  updatedAt?: string;
}
