/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';
import { environment } from '../../../environments/environment';

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
// export class ApiConfiguration {
//   rootUrl: string = 'http://localhost:8081';
// }

export class ApiConfiguration {
  rootUrl: string = environment.authApiUrl;
}
/**
 * Parameters for `ApiModule.forRoot()`
 */
export interface ApiConfigurationParams {
  rootUrl?: string;
}
