/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiResponseBoolean } from './models/api-response-boolean';
export type { ApiResponseListUserDto } from './models/api-response-list-user-dto';
export type { ApiResponseLoginResponse } from './models/api-response-login-response';
export type { ApiResponseMapStringObject } from './models/api-response-map-string-object';
export type { ApiResponseTenantDto } from './models/api-response-tenant-dto';
export type { ApiResponseUserDto } from './models/api-response-user-dto';
export type { ApiResponseVoid } from './models/api-response-void';
export type { CreateTenantRequest } from './models/create-tenant-request';
export type { LoginRequest } from './models/login-request';
export type { LoginResponse } from './models/login-response';
export type { RefreshTokenRequest } from './models/refresh-token-request';
export type { RegisterRequest } from './models/register-request';
export type { TenantDto } from './models/tenant-dto';
export type { UpdateUserRequest } from './models/update-user-request';
export type { UserDto } from './models/user-dto';
