/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileShareDto } from '../models/file-share-dto';
export interface ApiResponseFileShareDto {
  data?: FileShareDto;
  error?: string;
  message?: string;
  success?: boolean;
  timestamp?: string;
}
