/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageFileDto } from '../models/page-file-dto';
export interface ApiResponsePageFileDto {
  data?: PageFileDto;
  error?: string;
  message?: string;
  success?: boolean;
  timestamp?: string;
}
