/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FolderDto } from '../models/folder-dto';
export interface ApiResponseListFolderDto {
  data?: Array<FolderDto>;
  error?: string;
  message?: string;
  success?: boolean;
  timestamp?: string;
}
