/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileDto } from '../models/file-dto';
export interface ApiResponseFileDto {
  data?: FileDto;
  error?: string;
  message?: string;
  success?: boolean;
  timestamp?: string;
}
