/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FileShareDto {
  accessCount?: number;
  createdAt?: string;
  expiresAt?: string;
  fileId?: string;
  fileName?: string;
  id?: string;
  isActive?: boolean;
  isExpired?: boolean;
  isPublic?: boolean;
  lastAccessedAt?: string;
  permission?: 'READ' | 'DOWNLOAD' | 'WRITE';
  shareToken?: string;
  sharedBy?: string;
  sharedWith?: string;
}
