/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FolderDto {
  createdAt?: string;
  createdBy?: string;
  depth?: number;
  fileCount?: number;
  id?: string;
  isRoot?: boolean;
  name?: string;
  parentId?: string;
  path?: string;
  subfolderCount?: number;
  updatedAt?: string;
}
