/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ShareFileRequest {
  expiresAt?: string;
  message?: string;
  permission: 'READ' | 'DOWNLOAD' | 'WRITE';
  sharedWith?: string;
}
