/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationRequest {
  channel: 'EMAIL' | 'WEBSOCKET' | 'PUSH' | 'SMS';
  message?: string;
  metadata?: {
[key: string]: string;
};
  projectId?: number;
  recipientEmail?: string;
  scheduledFor?: string;
  taskId?: number;
  title: string;
  type: 'TASK_ASSIGNED' | 'TASK_UPDATED' | 'TASK_COMPLETED' | 'PROJECT_INVITATION' | 'PROJECT_UPDATED' | 'DEADLINE_REMINDER' | 'COMMENT_ADDED' | 'MENTION' | 'SYSTEM_ANNOUNCEMENT';
  userId: number;
}
