/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListFileDto } from '../../models/api-response-list-file-dto';

export interface GetFolderFiles$Params {
  folderId: string;
  Authorization: string;
}

export function getFolderFiles(http: HttpClient, rootUrl: string, params: GetFolderFiles$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListFileDto>> {
  const rb = new RequestBuilder(rootUrl, getFolderFiles.PATH, 'get');
  if (params) {
    rb.path('folderId', params.folderId, {});
    rb.header('Authorization', params.Authorization, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListFileDto>;
    })
  );
}

getFolderFiles.PATH = '/api/files/folder/{folderId}';
