/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseFileShareDto } from '../../models/api-response-file-share-dto';
import { ShareFileRequest } from '../../models/share-file-request';

export interface ShareFile$Params {
  fileId: string;
  Authorization: string;
      body: ShareFileRequest
}

export function shareFile(http: HttpClient, rootUrl: string, params: ShareFile$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseFileShareDto>> {
  const rb = new RequestBuilder(rootUrl, shareFile.PATH, 'post');
  if (params) {
    rb.path('fileId', params.fileId, {});
    rb.header('Authorization', params.Authorization, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseFileShareDto>;
    })
  );
}

shareFile.PATH = '/api/files/{fileId}/share';
