/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ApiResponseDashboardDto } from '../models/api-response-dashboard-dto';
import { ApiResponseProjectStatsDto } from '../models/api-response-project-stats-dto';
import { getDashboard } from '../fn/dashboard-controller/get-dashboard';
import { GetDashboard$Params } from '../fn/dashboard-controller/get-dashboard';
import { getProjectStats } from '../fn/dashboard-controller/get-project-stats';
import { GetProjectStats$Params } from '../fn/dashboard-controller/get-project-stats';

@Injectable({ providedIn: 'root' })
export class DashboardControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getDashboard()` */
  static readonly GetDashboardPath = '/api/dashboard';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDashboard()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDashboard$Response(params: GetDashboard$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseDashboardDto>> {
    return getDashboard(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDashboard$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDashboard(params: GetDashboard$Params, context?: HttpContext): Observable<ApiResponseDashboardDto> {
    return this.getDashboard$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiResponseDashboardDto>): ApiResponseDashboardDto => r.body)
    );
  }

  /** Path part for operation `getProjectStats()` */
  static readonly GetProjectStatsPath = '/api/dashboard/projects/{projectId}/stats';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectStats()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectStats$Response(params: GetProjectStats$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseProjectStatsDto>> {
    return getProjectStats(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectStats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectStats(params: GetProjectStats$Params, context?: HttpContext): Observable<ApiResponseProjectStatsDto> {
    return this.getProjectStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiResponseProjectStatsDto>): ApiResponseProjectStatsDto => r.body)
    );
  }

}
