/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseTenantDto } from '../../models/api-response-tenant-dto';

export interface GetCurrentTenant$Params {
}

export function getCurrentTenant(http: HttpClient, rootUrl: string, params?: GetCurrentTenant$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseTenantDto>> {
  const rb = new RequestBuilder(rootUrl, getCurrentTenant.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseTenantDto>;
    })
  );
}

getCurrentTenant.PATH = '/api/tenants/current';
