/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TenantDto } from '../models/tenant-dto';
export interface ApiResponseTenantDto {
  data?: TenantDto;
  message?: string;
  success?: boolean;
  timestamp?: string;
}
