/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiResponseVoid {
  data?: {
};
  message?: string;
  success?: boolean;
  timestamp?: string;
}
