/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LoginResponse } from '../models/login-response';
export interface ApiResponseLoginResponse {
  data?: LoginResponse;
  message?: string;
  success?: boolean;
  timestamp?: string;
}
