/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTenantRequest {
  adminEmail: string;
  adminFirstName: string;
  adminLastName: string;
  adminPassword: string;
  name: string;
  subdomain: string;
}
