/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';
export interface LoginResponse {
  accessToken?: string;
  expiresIn?: number;
  refreshToken?: string;
  tenant?: string;
  tokenType?: string;
  user?: UserDto;
}
