/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuickTaskRequest } from '../../models/quick-task-request';
import { SimpleTaskDto } from '../../models/simple-task-dto';

export interface CreateQuickTask$Params {
      body: QuickTaskRequest
}

export function createQuickTask(http: HttpClient, rootUrl: string, params: CreateQuickTask$Params, context?: HttpContext): Observable<StrictHttpResponse<SimpleTaskDto>> {
  const rb = new RequestBuilder(rootUrl, createQuickTask.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SimpleTaskDto>;
    })
  );
}

createQuickTask.PATH = '/api/test/tasks/quick';
