/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuickProjectRequest } from '../../models/quick-project-request';
import { SimpleProjectDto } from '../../models/simple-project-dto';

export interface CreateQuickProject$Params {
      body: QuickProjectRequest
}

export function createQuickProject(http: HttpClient, rootUrl: string, params: CreateQuickProject$Params, context?: HttpContext): Observable<StrictHttpResponse<SimpleProjectDto>> {
  const rb = new RequestBuilder(rootUrl, createQuickProject.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SimpleProjectDto>;
    })
  );
}

createQuickProject.PATH = '/api/test/projects/quick';
