/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SimpleTaskDto } from '../../models/simple-task-dto';

export interface GetProjectTasks$Params {
  projectId: string;
}

export function getProjectTasks(http: HttpClient, rootUrl: string, params: GetProjectTasks$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SimpleTaskDto>>> {
  const rb = new RequestBuilder(rootUrl, getProjectTasks.PATH, 'get');
  if (params) {
    rb.path('projectId', params.projectId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SimpleTaskDto>>;
    })
  );
}

getProjectTasks.PATH = '/api/test/projects/{projectId}/tasks';
