/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SimpleTaskDto } from '../../models/simple-task-dto';
import { UpdateTaskStatusRequest } from '../../models/update-task-status-request';

export interface UpdateTaskStatus$Params {
  taskId: string;
      body: UpdateTaskStatusRequest
}

export function updateTaskStatus(http: HttpClient, rootUrl: string, params: UpdateTaskStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<SimpleTaskDto>> {
  const rb = new RequestBuilder(rootUrl, updateTaskStatus.PATH, 'put');
  if (params) {
    rb.path('taskId', params.taskId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SimpleTaskDto>;
    })
  );
}

updateTaskStatus.PATH = '/api/test/tasks/{taskId}/status';
