/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponsePageTaskDto } from '../../models/api-response-page-task-dto';
import { Pageable } from '../../models/pageable';

export interface GetAllTasks1$Params {
  projectId?: string;
  pageable: Pageable;
  Authorization: string;
}

export function getAllTasks1(http: HttpClient, rootUrl: string, params: GetAllTasks1$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponsePageTaskDto>> {
  const rb = new RequestBuilder(rootUrl, getAllTasks1.PATH, 'get');
  if (params) {
    rb.query('projectId', params.projectId, {});
    rb.query('pageable', params.pageable, {});
    rb.header('Authorization', params.Authorization, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponsePageTaskDto>;
    })
  );
}

getAllTasks1.PATH = '/api/tasks';
