/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListTaskDto } from '../../models/api-response-list-task-dto';

export interface SearchTasks$Params {
  q: string;
  Authorization: string;
}

export function searchTasks(http: HttpClient, rootUrl: string, params: SearchTasks$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListTaskDto>> {
  const rb = new RequestBuilder(rootUrl, searchTasks.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.header('Authorization', params.Authorization, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListTaskDto>;
    })
  );
}

searchTasks.PATH = '/api/tasks/search';
