/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseProjectStatsDto } from '../../models/api-response-project-stats-dto';

export interface GetProjectStats$Params {
  projectId: string;
  Authorization: string;
}

export function getProjectStats(http: HttpClient, rootUrl: string, params: GetProjectStats$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseProjectStatsDto>> {
  const rb = new RequestBuilder(rootUrl, getProjectStats.PATH, 'get');
  if (params) {
    rb.path('projectId', params.projectId, {});
    rb.header('Authorization', params.Authorization, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseProjectStatsDto>;
    })
  );
}

getProjectStats.PATH = '/api/dashboard/projects/{projectId}/stats';
