/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddMemberRequest } from '../../models/add-member-request';
import { ApiResponseVoid } from '../../models/api-response-void';

export interface AddProjectMember$Params {
  projectId: string;
  Authorization: string;
      body: AddMemberRequest
}

export function addProjectMember(http: HttpClient, rootUrl: string, params: AddProjectMember$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseVoid>> {
  const rb = new RequestBuilder(rootUrl, addProjectMember.PATH, 'post');
  if (params) {
    rb.path('projectId', params.projectId, {});
    rb.header('Authorization', params.Authorization, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseVoid>;
    })
  );
}

addProjectMember.PATH = '/api/projects/{projectId}/members';
