/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListProjectDto } from '../../models/api-response-list-project-dto';

export interface GetAllProjects1$Params {
  Authorization: string;
}

export function getAllProjects1(http: HttpClient, rootUrl: string, params: GetAllProjects1$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListProjectDto>> {
  const rb = new RequestBuilder(rootUrl, getAllProjects1.PATH, 'get');
  if (params) {
    rb.header('Authorization', params.Authorization, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListProjectDto>;
    })
  );
}

getAllProjects1.PATH = '/api/projects';
