/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListProjectDto } from '../../models/api-response-list-project-dto';

export interface SearchProjects$Params {
  q: string;
  Authorization: string;
}

export function searchProjects(http: HttpClient, rootUrl: string, params: SearchProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListProjectDto>> {
  const rb = new RequestBuilder(rootUrl, searchProjects.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.header('Authorization', params.Authorization, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListProjectDto>;
    })
  );
}

searchProjects.PATH = '/api/projects/search';
