/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { TestControllerService } from './services/test-controller.service';
export { TaskControllerService } from './services/task-controller.service';
export { ProjectControllerService } from './services/project-controller.service';
export { KanbanControllerService } from './services/kanban-controller.service';
export { HealthControllerService } from './services/health-controller.service';
export { DashboardControllerService } from './services/dashboard-controller.service';
