/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseFolderDto } from '../../models/api-response-folder-dto';
import { CreateFolderRequest } from '../../models/create-folder-request';

export interface CreateFolder$Params {
  Authorization: string;
      body: CreateFolderRequest
}

export function createFolder(http: HttpClient, rootUrl: string, params: CreateFolder$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseFolderDto>> {
  const rb = new RequestBuilder(rootUrl, createFolder.PATH, 'post');
  if (params) {
    rb.header('Authorization', params.Authorization, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseFolderDto>;
    })
  );
}

createFolder.PATH = '/api/folders';
