/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListFolderDto } from '../../models/api-response-list-folder-dto';

export interface GetFolderTree$Params {
  Authorization: string;
}

export function getFolderTree(http: HttpClient, rootUrl: string, params: GetFolderTree$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListFolderDto>> {
  const rb = new RequestBuilder(rootUrl, getFolderTree.PATH, 'get');
  if (params) {
    rb.header('Authorization', params.Authorization, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListFolderDto>;
    })
  );
}

getFolderTree.PATH = '/api/folders';
